version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: echo 'rs.status().ok' | mongosh localhost:27017 --quiet
      interval: 5s
      timeout: 5s
      retries: 10

  mongo-secondary:
    image: mongo
    container_name: mongo-secondary
    ports:
      - "27018:27017"
    volumes:
      - mongo-secondary-data:/data/db
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    healthcheck:
      test: echo 'rs.status().ok' | mongosh localhost:27017 --quiet
      interval: 5s
      timeout: 5s
      retries: 10

  
  mongo-init:
    image: mongo
    depends_on:
      - mongo
      - mongo-secondary
    restart: "no"
    entrypoint: >
      bash -c "sleep 5 &&
      mongosh --host mongo --eval '
        rs.initiate({
          _id: \"rs0\",
          members: [
            { _id: 0, host: \"mongo:27017\" },
            { _id: 1, host: \"mongo-secondary:27017\", priority: 0 }
          ]
        })'"

  
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=5200
      - ME_CONFIG_MONGODB_URL=mongodb://mongo:27017,mongo-secondary:27017/?replicaSet=rs0


  backend:
    build: ./backend
    container_name: flask-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - PYTHONPATH=/app
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: react-frontend
    ports:
      - "5173:5173"  # Vite default port
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend  # if you have one


volumes:
  mongo-data:
  mongo-secondary-data:

